### ISSUE TITLE
ITUNES

### ISSUE THREAD

**Issue by MMAKENPO** [RYSKZ/Song-tags-search#1]
HELLO FROM GREECE!!!TELL ME PLEASE WE CAN SEARCH SONGS AND ALBUMS FROM ITUNES?AND IF YES,PLEASE COULD YOU TELL ME THE WEB?

**Comment by RYSKZ** [comment]
Hi, I think there is no web page where you can search directly, you can use this script if you want to do a search of a song or album, it will return the song metadata printed in the console.

The only website I know is this one: https://bendodson.com/projects/itunes-artwork-finder/

But it only works for the album cover.

**Comment by MMAKENPO** [comment]
OOOOO AAA OK MAN...THANKS SO MUCH!!!THIS IS YOURS?

**Comment by RYSKZ** [comment]
The website I linked? No, it's not mine, it's from Ben Dodson.

**Comment by MMAKENPO** [comment]
my friend how difficult is for someone where have no idea from developing and programming make one web where use api from itunes for songs and albums???

**Comment by RYSKZ** [comment]
It doesn't take so much time, you just need to feel comfortable with some programming language, know the basics for API usage and read the official documentation (https://affiliate.itunes.apple.com/resources/documentation/itunes-store-web-service-search-api/).

**Comment by MMAKENPO** [comment]
ooooooo it seems very difficult....my friend tell me please something!!!can you make one web where use itunes api for searchingsongs and albums with unlimited results?I preciate it so so so muchhhhhhhhhhhhhhh....unfortunately I am not rich to pay you for this!!!

**Comment by RYSKZ** [comment]
Sorry, I don't have time to do that. You may take the time to learn how to do it by yourself, it's not difficult, and it may be useful for you in the future.

Anyway, there is a limit in the search results, you can try to bypass it if you find the way.
